version: "3.7"
services:
  nginx:
    image: nginx:alpine
    container_name: auth-app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - auth-app-network

  app:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    container_name: auth-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
    ports:
      - 9000:9000
    depends_on:
      - mariadb
      - redis
    networks:
      - auth-app-network

  mariadb:
    image: mariadb:10.5.5
    container_name: auth-app-mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=interport_auth
    networks:
      - auth-app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    restart: always
    ports:
      - 8077:80
    networks:
      - auth-app-network

  redis:
    image: redis:alpine
    container_name: auth-app-redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    networks:
      - auth-app-network


networks:
  auth-app-network:
    driver: bridge


volumes:
  auth-app-volume:
    driver: local
